# Generated by Django 3.2.7 on 2021-12-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addemployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeefullname', models.CharField(max_length=20)),
                ('employeeplace', models.CharField(max_length=20)),
                ('employeephonenumber', models.BigIntegerField()),
                ('employeeemail', models.CharField(max_length=20)),
                ('employeepassword', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='addworkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshopname', models.CharField(max_length=20)),
                ('workshopplace', models.CharField(max_length=20)),
                ('phonenumber', models.BigIntegerField()),
                ('workshopemail', models.CharField(max_length=20)),
                ('workshoppassword', models.CharField(max_length=10)),
            ],
        ),
    ]
