# Generated by Django 3.2.7 on 2021-12-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addworkshop',
        ),
    ]
