# Generated by Django 3.2.7 on 2021-12-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_addworkshop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addemployees',
        ),
    ]
