# Generated by Django 3.2.7 on 2021-12-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_addemployees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployees',
            name='salary',
            field=models.BigIntegerField(null=True),
        ),
    ]
