# Generated by Django 3.2.7 on 2021-12-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_deletedworkshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='deletedemployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeefullname', models.CharField(max_length=20)),
                ('employeeplace', models.CharField(max_length=20)),
                ('employeephonenumber', models.BigIntegerField()),
                ('employeeemail', models.CharField(max_length=20)),
                ('employeepassword', models.CharField(max_length=10)),
                ('salary', models.BigIntegerField(null=True)),
            ],
        ),
    ]
