# Generated by Django 3.2.7 on 2022-01-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=50)),
                ('ModelName', models.CharField(max_length=50)),
                ('ManufacturedYear', models.CharField(max_length=10)),
                ('Purpose', models.CharField(max_length=20)),
                ('Contact', models.CharField(max_length=12)),
                ('OtherComplaints', models.CharField(max_length=300)),
                ('Address', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=10)),
                ('WorkshopId', models.CharField(max_length=8)),
                ('DateAndTime', models.CharField(max_length=60)),
            ],
        ),
    ]
