# Generated by Django 3.2.7 on 2022-01-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_auto_20220115_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='CustomerName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
