# Generated by Django 3.2.7 on 2022-01-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0003_customer_customername'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
