# Generated by Django 3.2.7 on 2022-01-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0005_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimatedprice', models.CharField(max_length=10)),
                ('st', models.CharField(max_length=10)),
                ('et', models.CharField(max_length=10)),
                ('cuid', models.CharField(max_length=10)),
            ],
        ),
    ]
