# Generated by Django 3.2.7 on 2022-01-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0006_expected'),
    ]

    operations = [
        migrations.CreateModel(
            name='liveValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
