# Generated by Django 3.2.7 on 2022-01-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0007_livevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='livevalue',
            name='bookingId',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
