# Generated by Django 3.2.7 on 2022-01-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0008_livevalue_bookingid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedWorkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuid', models.CharField(max_length=5)),
                ('FinishedWork', models.CharField(max_length=50)),
                ('ProductName', models.CharField(max_length=50)),
                ('TimeTaken', models.CharField(max_length=10)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
