# Generated by Django 3.2.7 on 2022-01-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0009_finishedworklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedworklist',
            name='Price',
            field=models.IntegerField(null=True),
        ),
    ]
