# Generated by Django 3.2.7 on 2021-12-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=400)),
                ('mainhead', models.CharField(max_length=40)),
                ('fsubhead', models.CharField(max_length=50)),
                ('ssubhead', models.CharField(max_length=40)),
            ],
        ),
    ]
