# Generated by Django 3.2.7 on 2022-01-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0002_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='cotactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=10)),
            ],
        ),
    ]
