# Generated by Django 3.2.7 on 2022-01-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0003_cotactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
    ]
