# Generated by Django 3.2.7 on 2022-01-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0004_custfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='product')),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=10)),
                ('stock', models.CharField(max_length=10)),
            ],
        ),
    ]
