# Generated by Django 3.2.7 on 2022-01-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullservicebooking',
            name='clid',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='fullservicebooking',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
