# Generated by Django 3.2.7 on 2022-01-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_waterservbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterservbooking',
            name='contact',
        ),
    ]
