# Generated by Django 3.2.7 on 2022-01-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0004_remove_waterservbooking_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterservbooking',
            name='contact',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
