# Generated by Django 3.2.7 on 2021-12-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='firstadvetisementpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advphoto', models.CharField(max_length=400)),
                ('mainhead', models.CharField(max_length=30)),
                ('firstsubhead', models.CharField(max_length=30)),
                ('secondsubhead', models.CharField(max_length=30)),
            ],
        ),
    ]
