# Generated by Django 3.2.7 on 2021-12-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_firstadvetisementpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='firstadvetisementpage',
        ),
    ]
