# Generated by Django 3.2.7 on 2021-12-27 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_deletedemployees'),
        ('app1', '0003_delete_firstadvetisementpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='workshopnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.addworkshop')),
            ],
        ),
    ]
