# Generated by Django 3.2.7 on 2022-01-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedwaterServ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=10)),
                ('cartype', models.CharField(max_length=11)),
                ('servtype', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=12)),
                ('ocomplaint', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=10)),
                ('watershopid', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('clientid', models.CharField(max_length=10)),
                ('DateAndTime', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='LiveValueWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuewater', models.CharField(max_length=200)),
                ('bookingId', models.CharField(max_length=10)),
            ],
        ),
    ]
